name: Tag Package 

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  node_tag:
    name: Tag Package Json

    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true  # Explicitly fetch tags
        
      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
          echo "Latest tag: $latest_tag"

      - name: Bump Version of package.json
        uses: ramonpaolo/bump-version@v2.3.1
        with:
          tag: ${{ steps.get_tag.outputs.latest_tag }}
          commit: true
          branch_to_push: 'main'
